;;;=============================================================================
;;; ELFEED FEEDS
;;;=============================================================================

(setopt
 elfeed-feeds
 '(("https://www.precociouscomic.com/rss.php" comic)
   ("https://www.qwantz.com/rssfeed.php" comic)
   ("https://existentialcomics.com/rss.xml" comic)
   ("https://www.smbc-comics.com/comic/rss" comic)
   ("https://xkcd.com/atom.xml" comic)
   ("https://batsov.com/atom.xml" emacs)
   ("https://emacsredux.com/atom.xml" emacs)
   ("https://irreal.org/blog/?feed=rss2" emacs)
   ("https://karthinks.com/index.xml" emacs)
   ("https://protesilaos.com/codelog.xml" emacs)
   ("https://sachachua.com/blog/feed" emacs)
   ("https://www.masteringemacs.org/feed" emacs)
   ("https://www.hardcoregaming101.net/feed" games)
   ("https://bay12games.com/dwarves/dev_now.rss" games)
   ("https://blog.minetest.net/feed.rss" games)
   ("https://crpgaddict.blogspot.com/feeds/posts/default" games)
   ("https://datadrivengamer.blogspot.com/feeds/posts/default" games)
   ("https://onemandoom.blogspot.com/feeds/posts/default" games)
   ("https://osu.ppy.sh/home/news?format=atom" games)
   ("https://theforceengine.github.io/atom.xml" games)
   ("https://blog.xfce.org/feed" libre)
   ("https://f-droid.org/feed.xml" libre)
   ("https://morss.it/https://blog.opensource.org/feed/" libre)
   ("https://neovim.io/news.xml" libre)
   ("https://planet.gnu.org/atom.xml" libre)
   ("https://reactos.org/index.xml" libre)
   ("https://www.haiku-os.org/index.xml" libre)
   ("https://archlinux.org/feeds/planet/" linux arch)
   ("https://archlinux.org/feeds/releases/" linux arch)
   ("https://distrowatch.com/news/dww.xml" linux)
   ("https://distrowatch.com/news/news-headlines.xml" linux)
   ("https://lwn.net/headlines/rss" linux)
   ("https://www.kernel.org/feeds/all.atom.xml" linux)
   ("https://blog.rust-lang.org/feed.xml" programming)
   ("https://go.dev/blog/feed.atom" programming)
   ("https://technomancy.us/atom.xml" programming)
   ("https://international.dsausa.org/statements/feed" misc)
   ("https://www.reddit.com/r/HobbyDrama/.rss" misc)
   ("https://www.accursedfarms.com/rss/3-accursed-farms.xml/" misc)
   ("https://www.dsausa.org/statements/feed" misc)
   ("https://medium.com/feed/@butchanarchy" misc)
   ("https://mars.nasa.gov/rss/api/?feed=blogs&category=mars2020&feedtype=rss"
    space perseverance)
   ("https://mars.nasa.gov/rss/api/?feed=blogs&category=msl&feedtype=rss"
    space curiosity)))
